-- MySQL Script generated by MySQL Workbench
-- 11/27/14 17:52:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `usuario` VARCHAR(12) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Concurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Concurso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Concurso` (
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `bases` VARCHAR(45) NOT NULL,
  `premios` VARCHAR(200) NOT NULL,
  `patrocinadores` VARCHAR(200) NOT NULL,
  `logo` VARCHAR(45) NOT NULL,
  `Admin_usuario` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`nombre`),
  CONSTRAINT `fk_Concurso_Admin1`
    FOREIGN KEY (`Admin_usuario`)
    REFERENCES `mydb`.`Admin` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Establecimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Establecimiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Establecimiento` (
  `nombre` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `horario` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `pagina_web` VARCHAR(45) NULL,
  `telefono` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pincho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pincho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pincho` (
  `idPincho` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `ingredientes` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NOT NULL,
  `Concurso_nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `Establecimiento_nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPincho`),
  CONSTRAINT `fk_Pincho_Concurso1`
    FOREIGN KEY (`Concurso_nombre`)
    REFERENCES `mydb`.`Concurso` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pincho_Establecimiento1`
    FOREIGN KEY (`Establecimiento_nombre`)
    REFERENCES `mydb`.`Establecimiento` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jurado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Jurado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Jurado` (
  `idJurado` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idJurado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Voto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Voto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Voto` (
  `idVoto` INT NOT NULL,
  `puntuacion` VARCHAR(45) NOT NULL,
  `Pincho_idPincho` INT NOT NULL,
  `Jurado_idJurado` INT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVoto`, `Jurado_idJurado`, `categoria`),
  CONSTRAINT `fk_Voto_Pincho1`
    FOREIGN KEY (`Pincho_idPincho`)
    REFERENCES `mydb`.`Pincho` (`idPincho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voto_Jurado1`
    FOREIGN KEY (`Jurado_idJurado`)
    REFERENCES `mydb`.`Jurado` (`idJurado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comentario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `idComentario` INT NOT NULL,
  `comentario` VARCHAR(200) NOT NULL,
  `Jurado_idJurado` INT NOT NULL,
  `Pincho_idPincho` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  CONSTRAINT `fk_Comentario_Jurado1`
    FOREIGN KEY (`Jurado_idJurado`)
    REFERENCES `mydb`.`Jurado` (`idJurado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Pincho1`
    FOREIGN KEY (`Pincho_idPincho`)
    REFERENCES `mydb`.`Pincho` (`idPincho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
